### ISSUE TITLE
Parse error when parsing app "LeetStats - LeetCode Analytics"

### ISSUE THREAD

**Issue by eric1932** [eric1932/AppStoreIconDownloader#1]
url: [https://apps.apple.com/cn/app/id1590820002](https://apps.apple.com/cn/app/id1590820002)

cause: some page doesn't have the element of version

error log:
```python
search keyword: leetcode
1.	力扣LeetCode - 算法编程职业成长社区on the App Store
	https://apps.apple.com/us/app/id1470936215
2.	App Store 上的“LeetStats - LeetCode Analytics”
	https://apps.apple.com/cn/app/id1590820002
select: 2
Traceback (most recent call last):
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/search.py", line 85, in <module>
    download_image(chosen_item['link'], False)
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/downloader.py", line 33, in download_image
    app_name, app_url_cleaned, app_version, img_ext, image_url_orig = get_orig_img_url(app_url)
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/appstore_parser.py", line 34, in get_orig_img_url
    app_name, app_version, img_ext, img_url_orig = _parse_appstore_html(print_log, web_html, store_url)
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/appstore_parser.py", line 15, in _parse_appstore_html
    app_metadata = AppMetadata(store_url, html_page=web_html)
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/AppMetadata.py", line 56, in __init__
    self._parse_metadata()
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/AppMetadata.py", line 88, in _parse_metadata
    self._parse_metadata_app_name_version()
  File "/Users/eric/PycharmProjects/AppStoreIconDownloader/AppMetadata.py", line 127, in _parse_metadata_app_name_version
    version = self._soup.find(
AttributeError: 'NoneType' object has no attribute 'next_element'
```

**Comment by eric1932** [comment]
Fixed #2
